---
- name: Tasks for app servers
  hosts: app
  become: true

  tasks:
    - name: Ensure chrony is installed
      ansible.builtin.apt:
        name: chrony
        state: present

    - name: Ensure chrony is started
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: true

- name: Tasks for db servers
  hosts: db
  become: true

  tasks:
    - name: Ensure curl is installed
      ansible.builtin.apt:
        name: curl
        state: present

